# Generated by Django 4.1.7 on 2023-07-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment_dailyquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(default='2ULMBMChiE', max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('dateofbirth', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Gender', max_length=10)),
                ('image', models.ImageField(blank=True, default='staff.png', null=True, upload_to='staff/')),
                ('designation', models.CharField(blank=True, choices=[('Administrator', 'Administrator'), ('Director', 'Director'), ('Accountant', 'Accountant'), ('Secretary', 'Secretary'), ('Security', 'Security'), ('Janitor', 'Janitor'), ('Cook', 'Cook'), ('Other', 'Other')], default='Other', max_length=50)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('contact2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Transfer', 'Transfer'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='New', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
