# Generated by Django 4.1.7 on 2023-06-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_orderroom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderroom',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.order'),
        ),
        migrations.AlterField(
            model_name='orderroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
    ]
