# Generated by Django 4.1.7 on 2023-06-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_category_room_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
    ]
